
services:

  wbs_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wbs_app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - wbs_network
  postgres:
    image: postgres:15-alpine
    container_name: wbs_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wallet"]
      interval: 10s
      timeout: 5s
      retries: 5

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: wbs_swagger_ui
    ports:
      - "8282:8080"
    volumes:
      - ./docs:/usr/share/nginx/html:ro
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/swagger.json 

  prometheus:
    image: prom/prometheus:latest
    container_name: wbs_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
    ports:
      - "9090:9090"
    depends_on:
      - postgres
      - wbs_app
    networks:
      - wbs_network

  grafana:
    image: grafana/grafana:latest
    container_name: wbs_grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: 'false'
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - wbs_network

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  wbs_network:
    driver: bridge

