global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'wallet-simulator'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:

  - job_name: 'wbs_app'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['wbs_app:8080']
        labels:
          service: 'wallet-balance-split'
          env: 'development'
