global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    service: 'wallet-balance-split'
    env: 'development'
    monitor: 'wallet-simulator'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alerts.yml"

scrape_configs:

  - job_name: 'wbs_app'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['wbs_app:8080']
        labels:
          component: 'api'

