definitions:
  models.BalanceResponse:
    properties:
      total:
        type: integer
      withdrawable:
        type: integer
    type: object
  models.ChargeRequest:
    properties:
      amount:
        type: integer
      idempotency_key:
        type: string
      release_at:
        type: string
      user_id:
        type: integer
    type: object
  models.ChargeResponse:
    properties:
      idempotency_key:
        type: string
      message:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
      status:
        type: integer
    type: object
  models.HealthResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  models.Transaction:
    properties:
      amount:
        description: positive for charge, negative for withdraw
        type: integer
      created_at:
        type: string
      id:
        type: integer
      release_at:
        description: optional for charge
        type: string
      status:
        description: '"pending", "completed", "failed"'
        type: string
      type:
        description: '"charge" or "withdraw"'
        type: string
      user_id:
        type: integer
    type: object
  models.WithdrawRequest:
    properties:
      amount:
        type: integer
      idempotency_key:
        type: string
      user_id:
        type: integer
    type: object
  models.WithdrawResponse:
    properties:
      idempotency_key:
        type: string
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /balance:
    get:
      consumes:
      - application/json
      description: Get Total and Withdrawable balance for a user
      parameters:
      - description: User ID
        in: query
        name: user_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Account Balance
          schema:
            $ref: '#/definitions/models.BalanceResponse'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get Account Balance
      tags:
      - balance
  /charge:
    post:
      consumes:
      - application/json
      description: Charge a user's account with a specified amount
      parameters:
      - description: Charge Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ChargeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Charge Successful
          schema:
            $ref: '#/definitions/models.ChargeResponse'
        "400":
          description: Invalid Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Charge Account
      tags:
      - charge
  /health:
    get:
      consumes:
      - application/json
      description: Check service health and database connection
      produces:
      - application/json
      responses:
        "200":
          description: Service is healthy
          schema:
            $ref: '#/definitions/models.HealthResponse'
        "500":
          description: Service is unhealthy
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Check Service Health
      tags:
      - health
  /transactions:
    get:
      consumes:
      - application/json
      description: Get the list of all transactions for a user
      parameters:
      - description: User ID
        in: query
        name: user_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Transaction List
          schema:
            items:
              $ref: '#/definitions/models.Transaction'
            type: array
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get Transaction History
      tags:
      - transactions
  /withdraw:
    post:
      consumes:
      - application/json
      description: Request to withdraw amount from account (request is deferred)
      parameters:
      - description: Withdraw Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.WithdrawRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Withdraw request received
          schema:
            $ref: '#/definitions/models.WithdrawResponse'
        "400":
          description: Invalid Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Withdraw Request
      tags:
      - withdraw
swagger: "2.0"
